### OpenAPI document
GET http://localhost:5274/swagger/v1/swagger.json
Accept: application/json

###

### Get all tickets
GET http://localhost:5274/api/tickets
Accept: application/json

###

### Get missing ticket
GET http://localhost:5274/api/tickets/9999
Accept: application/json

###

### Create valid ticket
POST http://localhost:5274/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Printer broken",
  "description": "Office printer not working"
}

###

### Create invalid ticket - validation error
POST http://localhost:5274/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "",
  "description": "Office printer not working"
}

###

### Update ticket status
PATCH http://localhost:5274/api/tickets/1/status
Content-Type: application/json
Accept: application/json

{
  "status": 2
}


###

### Check security headers
GET http://localhost:5274/
Accept: text/html

###

### Create invalid ticket - empty title
POST http://localhost:5274/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "",
  "description": "Office printer not working"
}

###

### Create invalid ticket - empty description
POST http://localhost:5274/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Printer broken",
  "description": ""
}

###

### Create invalid ticket - too long title
POST http://localhost:5274/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "description": "Office printer not working"
}

###

### MVC Create without anti-forgery token - should be rejected
POST http://localhost:5274/Tickets/Create
Content-Type: application/x-www-form-urlencoded

Title=CSRF test&Description=Request without token

### LAB 10 CORE - Minimal API v2 - Get all tickets
GET http://localhost:5274/api/v2/tickets
Accept: application/json

###

### LAB 10 CORE - Minimal API v2 - Create ticket
POST http://localhost:5274/api/v2/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Ticket from Minimal API v2",
  "description": "Created during LAB 10 CORE"
}

###

### LAB 10 CORE - Minimal API v2 - Delete ticket
DELETE http://localhost:5274/api/v2/tickets/13
Accept: application/json

### LAB 10 STRETCH - Minimal API v2 - Update ticket
PUT http://localhost:5274/api/v2/tickets/13
Content-Type: application/json
Accept: application/json

{
  "title": "Updated ticket from LAB 10 STRETCH",
  "description": "Updated by PUT endpoint in Minimal API v2",
  "status": 1
}

###

### LAB 10 STRETCH - Minimal API v2 - Delete missing ticket - ProblemDetails 404
DELETE http://localhost:5274/api/v2/tickets/9999
Accept: application/json

###

### LAB 10 STRETCH - Minimal API v2 - Update missing ticket - ProblemDetails 404
PUT http://localhost:5274/api/v2/tickets/9999
Content-Type: application/json
Accept: application/json

{
  "title": "Missing ticket",
  "description": "This should return ProblemDetails",
  "status": 1
}


### LAB 10 AMBITNE - Minimal API v2 - Validation error
POST http://localhost:5274/api/v2/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "",
  "description": ""
}

###

### LAB 10 AMBITNE - Minimal API v2 - Validation error PUT
PUT http://localhost:5274/api/v2/tickets/9999
Content-Type: application/json
Accept: application/json

{
  "title": "",
  "description": "",
  "status": 1
}


### LAB 11 CORE - Protected API without login
GET http://localhost:5274/api/tickets
Accept: application/json

### STRETCH - DELETE without login should return 401
DELETE http://localhost:5274/api/tickets/1
Accept: application/json


@baseUrl = http://localhost:5274

### LAB 11 AMBITNE - Login Admin
POST http://localhost:5274/api/ambitne/login
Content-Type: application/json

{
  "email": "admin@unidesk.local",
  "password": "Admin123!"
}


### LAB 11 AMBITNE - Minimal API without token should return 401
GET http://localhost:5274/api/ambitne/tickets
Accept: application/json


### LAB 11 AMBITNE - Minimal API with Admin token should return 200
GET http://localhost:5274/api/ambitne/tickets
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXosmqV7-b8wfJFxthX7Bgu29AJxTRKKxpFH2cVIup_QwKN3OrxnPc4rge0DCdM-zLJmiqA8AjNwoBRvtY-bcnkXdPopkwKyZusuAxJ1mUI_izC0Hlkou_IBKpCpMAxy05sGjD_lhOQthjFWQb3WLefpTMT2JskA5bXbqdE_uHGrhonGymw39K36rMmIWn53AVuCmTV8KldccJzDHOfHnAEQnTAfZ8L0Lp3xPlrNcAWT_nYArvuG9z-ulIpq1xYj9r1pMpHdykB-dCezINFVychwFl40sbG6bkvriRmXKOkur6HhEYCa9dMnC8WMerqodlyfUZBnwwl33NoLDtQDGJTmo4mxI7MloVCzIVHOLwJHpVwD9OIWU79uSMzHJHYMF5aJfjE08OjMn_skA7rH8wbgADjUm0o5el4xIS7pswnFdl7C5Os3d0flBNSjdcN6z6uG5wGHmlJztBOYZn9tBUJtWBgCLhdQWTHotkt3Oy0i7FLgHD27iC94FqsNg0eXKJTqLlEKtpgFV4oVDb9cu8df_Iw7HRClmRtUHri3ocBYvnz6HBWxossysDxw9PD66exqKhQ7lecpLAkkfXPIN0mExHOyBzxfhAFuaRV-DgMYbdjj8oxoDv9RYm56I-dOvQB0OAhIKrdRJpmcp6e3Y69JDNiqS_8Y295EjD4mCovStj1DK-TlFBQSG4N6I32nC-JEaOTF2oP3raF-Kqc5EzQWCnJXUJe79mHkh20SAGiJVOcb1jfionxbgijudsaoWCKkTNjDwWhSxpyKzKoq8OGC5Q13QX_PwG9zQgexwZ7vth1CyzpAMZjz4C1vxQiNo_M
Accept: application/json


### LAB 11 AMBITNE - Admin claim EmployeeId should return 200
GET http://localhost:5274/api/ambitne/tickets/me
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXosmqV7-b8wfJFxthX7Bgu29AJxTRKKxpFH2cVIup_QwKN3OrxnPc4rge0DCdM-zLJmiqA8AjNwoBRvtY-bcnkXdPopkwKyZusuAxJ1mUI_izC0Hlkou_IBKpCpMAxy05sGjD_lhOQthjFWQb3WLefpTMT2JskA5bXbqdE_uHGrhonGymw39K36rMmIWn53AVuCmTV8KldccJzDHOfHnAEQnTAfZ8L0Lp3xPlrNcAWT_nYArvuG9z-ulIpq1xYj9r1pMpHdykB-dCezINFVychwFl40sbG6bkvriRmXKOkur6HhEYCa9dMnC8WMerqodlyfUZBnwwl33NoLDtQDGJTmo4mxI7MloVCzIVHOLwJHpVwD9OIWU79uSMzHJHYMF5aJfjE08OjMn_skA7rH8wbgADjUm0o5el4xIS7pswnFdl7C5Os3d0flBNSjdcN6z6uG5wGHmlJztBOYZn9tBUJtWBgCLhdQWTHotkt3Oy0i7FLgHD27iC94FqsNg0eXKJTqLlEKtpgFV4oVDb9cu8df_Iw7HRClmRtUHri3ocBYvnz6HBWxossysDxw9PD66exqKhQ7lecpLAkkfXPIN0mExHOyBzxfhAFuaRV-DgMYbdjj8oxoDv9RYm56I-dOvQB0OAhIKrdRJpmcp6e3Y69JDNiqS_8Y295EjD4mCovStj1DK-TlFBQSG4N6I32nC-JEaOTF2oP3raF-Kqc5EzQWCnJXUJe79mHkh20SAGiJVOcb1jfionxbgijudsaoWCKkTNjDwWhSxpyKzKoq8OGC5Q13QX_PwG9zQgexwZ7vth1CyzpAMZjz4C1vxQiNo_M
Accept: application/json


### LAB 11 AMBITNE - Admin DELETE should return 204 or 404
DELETE http://localhost:5274/api/ambitne/tickets/8
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXosmqV7-b8wfJFxthX7Bgu29AJxTRKKxpFH2cVIup_QwKN3OrxnPc4rge0DCdM-zLJmiqA8AjNwoBRvtY-bcnkXdPopkwKyZusuAxJ1mUI_izC0Hlkou_IBKpCpMAxy05sGjD_lhOQthjFWQb3WLefpTMT2JskA5bXbqdE_uHGrhonGymw39K36rMmIWn53AVuCmTV8KldccJzDHOfHnAEQnTAfZ8L0Lp3xPlrNcAWT_nYArvuG9z-ulIpq1xYj9r1pMpHdykB-dCezINFVychwFl40sbG6bkvriRmXKOkur6HhEYCa9dMnC8WMerqodlyfUZBnwwl33NoLDtQDGJTmo4mxI7MloVCzIVHOLwJHpVwD9OIWU79uSMzHJHYMF5aJfjE08OjMn_skA7rH8wbgADjUm0o5el4xIS7pswnFdl7C5Os3d0flBNSjdcN6z6uG5wGHmlJztBOYZn9tBUJtWBgCLhdQWTHotkt3Oy0i7FLgHD27iC94FqsNg0eXKJTqLlEKtpgFV4oVDb9cu8df_Iw7HRClmRtUHri3ocBYvnz6HBWxossysDxw9PD66exqKhQ7lecpLAkkfXPIN0mExHOyBzxfhAFuaRV-DgMYbdjj8oxoDv9RYm56I-dOvQB0OAhIKrdRJpmcp6e3Y69JDNiqS_8Y295EjD4mCovStj1DK-TlFBQSG4N6I32nC-JEaOTF2oP3raF-Kqc5EzQWCnJXUJe79mHkh20SAGiJVOcb1jfionxbgijudsaoWCKkTNjDwWhSxpyKzKoq8OGC5Q13QX_PwG9zQgexwZ7vth1CyzpAMZjz4C1vxQiNo_M
Accept: application/json


### LAB 11 AMBITNE - Login normal user Varya
POST http://localhost:5274/api/ambitne/login
Content-Type: application/json

{
  "email": "varya@gmail.com",
  "password": "Meduza2004"
}


### LAB 11 AMBITNE - Normal user claim EmployeeId should return 200
GET http://localhost:5274/api/ambitne/tickets/me
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXplbwCADgp6pbI3PeWBenNz7ftMj-TbmwCTvsHyO2855n9KKrG2Vs7DRcbuUm5Fxy6SAWpfNceXzZFv7iXlmiDcxHKocd4jJPM0ezi3YYnsSlph-8AfBA-ni4a91PauJZLUDodZWy6S05PJcFiN8GO1ijmr63N29S05H2bFMGu6VYvaO4IGS0Ky0Wo0u8Lb_Vp1yWKhtM_QupDwqo_ITyKOx-wK4W_kBoHYD2oSLejU4GmwKINX-5M1WtaAQ_uvk-7QnWWr8Hsr_0SDJ6SDcc3Lhltihy2HtXh0a_pdcNR1pmWiCrSyF7xJuJ7-9BLuq-WqYAePf7cVRcAQWeRdt65TMgdFVLABIM9SdNwZreN1EEkKqntA1duOAEcJ3wgE7NlNaBxI9vsgThXK4xBqEsYQT6oYUnN99KI9Lxjdzmh6hJZYBO1h2getGSgLwMusZAJMUEcWkI4e7okq37YY4XbfL-ib-njyw9BOz78MOGgjT02WDXhoserkaD-m9KzHj88ut749Vfn7jLF2DTMLm0oWiyrfAkPL44X0PSFevoGTys132EhxjsF2ua3hYyzunYdLmC5o2p1kMrsMRmE9_9Vtmof2opG9KaQY0xe6UwPs50QodkjFqiRhCkrgRlPDeJfMEqbgvGWdJP6fOloB8bVR
Accept: application/json


### LAB 11 AMBITNE - Normal user DELETE should return 403
DELETE http://localhost:5274/api/ambitne/tickets/1
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXplbwCADgp6pbI3PeWBenNz7ftMj-TbmwCTvsHyO2855n9KKrG2Vs7DRcbuUm5Fxy6SAWpfNceXzZFv7iXlmiDcxHKocd4jJPM0ezi3YYnsSlph-8AfBA-ni4a91PauJZLUDodZWy6S05PJcFiN8GO1ijmr63N29S05H2bFMGu6VYvaO4IGS0Ky0Wo0u8Lb_Vp1yWKhtM_QupDwqo_ITyKOx-wK4W_kBoHYD2oSLejU4GmwKINX-5M1WtaAQ_uvk-7QnWWr8Hsr_0SDJ6SDcc3Lhltihy2HtXh0a_pdcNR1pmWiCrSyF7xJuJ7-9BLuq-WqYAePf7cVRcAQWeRdt65TMgdFVLABIM9SdNwZreN1EEkKqntA1duOAEcJ3wgE7NlNaBxI9vsgThXK4xBqEsYQT6oYUnN99KI9Lxjdzmh6hJZYBO1h2getGSgLwMusZAJMUEcWkI4e7okq37YY4XbfL-ib-njyw9BOz78MOGgjT02WDXhoserkaD-m9KzHj88ut749Vfn7jLF2DTMLm0oWiyrfAkPL44X0PSFevoGTys132EhxjsF2ua3hYyzunYdLmC5o2p1kMrsMRmE9_9Vtmof2opG9KaQY0xe6UwPs50QodkjFqiRhCkrgRlPDeJfMEqbgvGWdJP6fOloB8bVR
Accept: application/json


### LAB 11 AMBITNE - Normal user wrong email domain should return 403
GET http://localhost:5274/api/ambitne/tickets/domain-resource
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXplbwCADgp6pbI3PeWBenNz7ftMj-TbmwCTvsHyO2855n9KKrG2Vs7DRcbuUm5Fxy6SAWpfNceXzZFv7iXlmiDcxHKocd4jJPM0ezi3YYnsSlph-8AfBA-ni4a91PauJZLUDodZWy6S05PJcFiN8GO1ijmr63N29S05H2bFMGu6VYvaO4IGS0Ky0Wo0u8Lb_Vp1yWKhtM_QupDwqo_ITyKOx-wK4W_kBoHYD2oSLejU4GmwKINX-5M1WtaAQ_uvk-7QnWWr8Hsr_0SDJ6SDcc3Lhltihy2HtXh0a_pdcNR1pmWiCrSyF7xJuJ7-9BLuq-WqYAePf7cVRcAQWeRdt65TMgdFVLABIM9SdNwZreN1EEkKqntA1duOAEcJ3wgE7NlNaBxI9vsgThXK4xBqEsYQT6oYUnN99KI9Lxjdzmh6hJZYBO1h2getGSgLwMusZAJMUEcWkI4e7okq37YY4XbfL-ib-njyw9BOz78MOGgjT02WDXhoserkaD-m9KzHj88ut749Vfn7jLF2DTMLm0oWiyrfAkPL44X0PSFevoGTys132EhxjsF2ua3hYyzunYdLmC5o2p1kMrsMRmE9_9Vtmof2opG9KaQY0xe6UwPs50QodkjFqiRhCkrgRlPDeJfMEqbgvGWdJP6fOloB8bVR
Accept: application/json


### LAB 11 AMBITNE - Login domain user
POST http://localhost:5274/api/ambitne/login
Content-Type: application/json

{
  "email": "employee@top-uni.edu.pl",
  "password": "Employee123!"
}


### LAB 11 AMBITNE - Domain user can access domain resource should return 200
GET http://localhost:5274/api/ambitne/tickets/domain-resource
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXr2CAzjlnKHgKvy_-0RrIDJgrEgsakw-mxiG6Mo_Z_0DYAjrhYNV7hRor7hKZLWTAGUMm-17hHnN35Q-d-98U34tpdtlawUXMUH60pWY2LFVDZztLT_nSX7m3834-v0ZIVGQRcc65DhZHK3XG3ac09Ky7-IrLcYCiFMTzXVg7G8RIgnJbTaxdwVaQzo9NsRnCdtIyU5ox6N5G9k_IPdvqdwZN4vKkmBhzr3YFYMrm4x8SbkxJ_MjlevaaAShHPoEJsosbFMvrFYDsyyAa7B9UtPWWClMd6tS-wONkyuUBWAPOTABvulijd10Y6vomqoUER96Mfe1ehJfy7yM2fhs9w-ZgRm8TWLstzvJKY05mitk7N1LBqbLqBrBvYUhNuswY3-16j_Ds9hVF_37VrZK1mLxve9wN6GgBulPym7W_1Dl1kZRPbfRk0UNygBJL6dNpMyPjse9B1cveyTY-txKuQWFvQzjbRde26bu2gNsu664XtMK6ttGkU6rnrY170iONbA_N1l3t514LdImiURLoeAkk4wJx8Xxy_yN0-BTKM6Qak8xW8wZtpXklitYA-cPHoKAEg9ToiSD5z8ZExvzOquySvFkIT2oJreWLjtES4p5Y32ywxRUZGzMCrgTfkY1PU8gmWJFtj4VwVijgW-iaay5ECNzfzdmR3B62HL4vC63b32gi0Efgj_yN_xRIBeig3LWcVCj5oAfpZpCxf8gSKt
Accept: application/json


### LAB 11 AMBITNE - Domain user DELETE should return 403
DELETE http://localhost:5274/api/ambitne/tickets/1
Authorization: Bearer CfDJ8DlTfoyHx9VOs-4nkpBVRXr2CAzjlnKHgKvy_-0RrIDJgrEgsakw-mxiG6Mo_Z_0DYAjrhYNV7hRor7hKZLWTAGUMm-17hHnN35Q-d-98U34tpdtlawUXMUH60pWY2LFVDZztLT_nSX7m3834-v0ZIVGQRcc65DhZHK3XG3ac09Ky7-IrLcYCiFMTzXVg7G8RIgnJbTaxdwVaQzo9NsRnCdtIyU5ox6N5G9k_IPdvqdwZN4vKkmBhzr3YFYMrm4x8SbkxJ_MjlevaaAShHPoEJsosbFMvrFYDsyyAa7B9UtPWWClMd6tS-wONkyuUBWAPOTABvulijd10Y6vomqoUER96Mfe1ehJfy7yM2fhs9w-ZgRm8TWLstzvJKY05mitk7N1LBqbLqBrBvYUhNuswY3-16j_Ds9hVF_37VrZK1mLxve9wN6GgBulPym7W_1Dl1kZRPbfRk0UNygBJL6dNpMyPjse9B1cveyTY-txKuQWFvQzjbRde26bu2gNsu664XtMK6ttGkU6rnrY170iONbA_N1l3t514LdImiURLoeAkk4wJx8Xxy_yN0-BTKM6Qak8xW8wZtpXklitYA-cPHoKAEg9ToiSD5z8ZExvzOquySvFkIT2oJreWLjtES4p5Y32ywxRUZGzMCrgTfkY1PU8gmWJFtj4VwVijgW-iaay5ECNzfzdmR3B62HL4vC63b32gi0Efgj_yN_xRIBeig3LWcVCj5oAfpZpCxf8gSKt
Accept: application/json